"""
youtube_api_client.py — YTC Module
Echo Personal Memory System

Fetches video metadata from YouTube Data API v3 using OAuth 2.0.
Uses token_youtube.json generated by scripts/test_youtube_auth.py.
Tokens auto-refresh when expired — no manual intervention needed.

Why OAuth over API Key:
    - Consistent with Gmail module auth pattern
    - Future: access Watch Later, subscriptions, liked videos, playlists
    - Token already exists from initial setup — zero extra work
    - Same free quota: 10,000 units/day, 1 unit per video fetch

Requires:
    credentials.json   — in project root (from Google Cloud Console)
    token_youtube.json — in project root (generated by test_youtube_auth.py)
"""

import logging
import re
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

load_dotenv()
logger = logging.getLogger(__name__)

# Paths — resolved relative to project root
PROJECT_ROOT = Path(__file__).parent.parent.parent
TOKEN_PATH = PROJECT_ROOT / "token_youtube.json"
CREDENTIALS_PATH = PROJECT_ROOT / "credentials.json"

SCOPES = ["https://www.googleapis.com/auth/youtube.readonly"]


def get_youtube_client():
    """
    Build and return an authenticated YouTube Data API v3 client.
    Loads token_youtube.json and auto-refreshes if expired.
    Re-runs OAuth flow only if token is completely missing or revoked.
    """
    creds = None

    # Load existing token
    if TOKEN_PATH.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_PATH), SCOPES)

    # Auto-refresh if expired — this is the key piece
    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
            with open(TOKEN_PATH, "w") as f:
                f.write(creds.to_json())
            logger.info("YouTube OAuth token refreshed successfully")
        except Exception as e:
            logger.error(f"Token refresh failed: {e}")
            creds = None

    # Fallback — re-run OAuth flow if no valid creds
    if not creds or not creds.valid:
        if not CREDENTIALS_PATH.exists():
            raise FileNotFoundError(
                f"credentials.json not found at {CREDENTIALS_PATH}. "
                "Get it from Google Cloud Console and place in project root."
            )
        from google_auth_oauthlib.flow import InstalledAppFlow
        flow = InstalledAppFlow.from_client_secrets_file(
            str(CREDENTIALS_PATH), SCOPES
        )
        creds = flow.run_local_server(port=0)
        with open(TOKEN_PATH, "w") as f:
            f.write(creds.to_json())
        logger.info("YouTube OAuth flow completed — token saved")

    return build("youtube", "v3", credentials=creds)


def parse_iso8601_duration(duration: str) -> int:
    """
    Convert ISO 8601 duration string to total seconds.

    Examples:
        PT5M30S  → 330
        PT1H2M3S → 3723
        PT45S    → 45
        PT0S     → 0
    """
    if not duration:
        return 0
    pattern = r"PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?"
    match = re.match(pattern, duration)
    if not match:
        return 0
    hours = int(match.group(1) or 0)
    minutes = int(match.group(2) or 0)
    seconds = int(match.group(3) or 0)
    return hours * 3600 + minutes * 60 + seconds


async def fetch_video_metadata(video_id: str) -> Optional[dict]:
    """
    Fetch video metadata from YouTube Data API v3 using OAuth.

    Returns dict with: title, description, channel_name, channel_id,
    published_at, duration_seconds, category_id, tags
    or None if fetch fails.

    Falls back to stub data if OAuth not set up — ingestion continues
    without crashing, metadata just shows [STUB] until fixed.
    """
    try:
        youtube = get_youtube_client()

        response = youtube.videos().list(
            part="snippet,contentDetails",
            id=video_id
        ).execute()

        items = response.get("items", [])
        if not items:
            logger.warning(f"No metadata found for video_id={video_id}")
            return None

        item = items[0]
        snippet = item.get("snippet", {})
        content_details = item.get("contentDetails", {})

        duration_seconds = parse_iso8601_duration(
            content_details.get("duration", "PT0S")
        )

        metadata = {
            "title": snippet.get("title", ""),
            "description": snippet.get("description", ""),
            "channel_name": snippet.get("channelTitle", ""),
            "channel_id": snippet.get("channelId", ""),
            "published_at": snippet.get("publishedAt", ""),
            "duration_seconds": duration_seconds,
            "category_id": snippet.get("categoryId", ""),
            "tags": snippet.get("tags", []),
        }

        logger.info(
            f"Metadata fetched — video_id={video_id} "
            f"title='{metadata['title']}' duration={duration_seconds}s"
        )
        return metadata

    except FileNotFoundError as e:
        logger.error(f"Auth setup incomplete: {e}")
        return _stub_metadata(video_id)

    except HttpError as e:
        if e.resp.status == 403:
            logger.error("YouTube API quota exceeded or OAuth scope insufficient")
        elif e.resp.status == 404:
            logger.warning(f"Video not found: video_id={video_id}")
        else:
            logger.error(f"YouTube API HTTP error {e.resp.status}: {e}")
        return None

    except Exception as e:
        logger.error(f"Unexpected error for video_id={video_id}: {e}")
        return _stub_metadata(video_id)


def _stub_metadata(video_id: str) -> dict:
    """
    Stub metadata when OAuth is not configured.
    [STUB] prefix makes these easy to find and clean up in DB.
    """
    return {
        "title": f"[STUB] Video {video_id}",
        "description": "[STUB] OAuth not configured",
        "channel_name": "[STUB] Channel",
        "channel_id": "STUB_CHANNEL_ID",
        "published_at": "2026-01-01T00:00:00Z",
        "duration_seconds": 0,
        "category_id": "",
        "tags": [],
    }